AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Pronunciation Checker application'

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair
  
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
    ConstraintDescription: Must be a valid EC2 instance type
  
  GoogleApiKey:
    Description: Google Gemini API Key
    Type: String
    NoEcho: true
    MinLength: 1
    ConstraintDescription: Google API Key is required

  SSHLocation:
    Description: IP address range that can SSH to the EC2 instance
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c55b159cbfafe1f0
    us-west-2:
      AMI: ami-0d1cd67c26f5fca19
    eu-west-1:
      AMI: ami-0d71ea30463e0ff8d
    ap-southeast-1:
      AMI: ami-0c802847a7dd848c0

Resources:
  PronunciationCheckerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Pronunciation Checker
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: pronunciation-checker-sg

  PronunciationCheckerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref PronunciationCheckerSecurityGroup
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Update system
          apt-get update
          apt-get upgrade -y
          
          # Install dependencies
          apt-get install -y python3 python3-pip python3-venv nginx git supervisor
          
          # Clone repository (update with your repo URL)
          cd /home/ubuntu
          # git clone https://github.com/yourusername/pronunciation-checker.git
          
          # Create .env file
          cat > /home/ubuntu/pronuciation_checker/.env << EOF
          GOOGLE_API_KEY=${GoogleApiKey}
          SECRET_KEY=$(openssl rand -hex 32)
          UPLOAD_FOLDER=./uploads
          FLASK_ENV=production
          EOF
          
          # Set permissions
          chown -R ubuntu:ubuntu /home/ubuntu/pronuciation_checker
          
          echo "Instance setup completed"
      Tags:
        - Key: Name
          Value: pronunciation-checker-server

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref PronunciationCheckerInstance
      Tags:
        - Key: Name
          Value: pronunciation-checker-eip

Outputs:
  InstanceId:
    Description: Instance ID
    Value: !Ref PronunciationCheckerInstance
  
  PublicIP:
    Description: Public IP address
    Value: !Ref ElasticIP
  
  PublicDNS:
    Description: Public DNS name
    Value: !GetAtt PronunciationCheckerInstance.PublicDnsName
  
  SSHCommand:
    Description: SSH command to connect
    Value: !Sub 'ssh -i ${KeyName}.pem ubuntu@${ElasticIP}'
  
  ApplicationURL:
    Description: Application URL
    Value: !Sub 'http://${ElasticIP}'
